
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.14.2"
minimal_mistakes_skin: "dark"

title: "3DP for Dummies"
title_separator: "|"
author:
  name     : "Roberto Lo Giacco"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Rome, IT"
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://rlogiacco.wordpress.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rlogiacco"
footer:
  links:
    - label: "AgileWare"
      icon: "fas fa-fw fa-link"
      url: "https://agileware.org"
search: false
#search_provider: algolia
defaults:
  - 
    scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main"